apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: greeting-service
  labels:
    app: greeting-service
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: greeting-service
    weight: 100
  wildcardPolicy: None
  tls:
    insecureEdgeTerminationPolicy: Redirect