apiVersion: v1
kind: Service
metadata:
  name: greeting-service
  labels:
    app: greeting-service
spec:
  type: ClusterIP
  selector:
    app: greeting-service
  sessionAffinity: None
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
